model:
  name: resnet50_fc512
  pretrained: True
data:
  type: image
  root: reid-data
  sources: [wildtiger]
  targets: [wildtiger]
  height: 128
  width: 256
  transforms: [color_jitter, random_erase]
  save_dir: log/wildtiger_video_triplet
sampler:
  train_sampler: RandomIdentityVideoSampler
  num_instances: 8
  video_batch_probability: 0.5
loss:
  name: triplet
  triplet:
    margin: 0.3
    weight_t: 0.5
    weight_cv: 1.0
    weight_x: 1.0
train:
  batch_size: 64
  optim: amsgrad
  lr: 0.0003
  max_epoch: 60
